all : fifoget fifoskp fiforev fifoply

fifoget : fifoget.c
	gcc -o fifoget fifoget.c

fifoskp : fifoskp.c
	gcc -o fifoskp fifoskp.c

fiforev : fiforev.c
	gcc -o fiforev fiforev.c

fifoply : fifoply.c
	gcc -o fifoply fifoply.c

.PHONY : all